
function (find_submodule name path)
    if (EXISTS ../../${name})
        set (${path} ../../${name} PARENT_SCOPE)
    elseif (EXISTS ${3rdPARTY_DIR}/${name})
        set (${path} ${3rdPARTY_DIR}/${name} PARENT_SCOPE)
    endif()
endfunction()

if (NOT EXISTS ${psi_comm_dir})
    set (psi_comm_dir "")
    find_submodule(psi-comm psi_comm_dir)
    message("psi_comm_dir: ${psi_comm_dir}")
    if (NOT EXISTS ${psi_comm_dir})
        add_subdirectory(3rdparty/psi-comm)
    endif()
endif()

if (NOT EXISTS ${psi_tools_dir})
    set (psi_tools_dir "")
    find_submodule(psi-tools psi_tools_dir)
    message("psi_tools_dir: ${psi_tools_dir}")
    if (NOT EXISTS ${psi_tools_dir})
        add_subdirectory(3rdparty/psi-tools)
    endif()
endif()